import React from 'react'
import styled from 'styled-components'
import { breakPoint } from '../constants/variable'

export default () => (
  <Container>
    <Spacer />
    <Inner>
      <h1 id="privacypolicy">Privacy Policy</h1>

      <h2 id="effectivedatedecember232018">Effective date: December 23, 2018</h2>

      <p>Elastos Application Lab ("us", "we", or "our") operates the Elephant Wallet mobile application (the "Service").</p>

      <p>This page informs you of our policies regarding the collection, use, and disclosure of personal data when you use our Service and the choices you have associated with that data.</p>

      <p>We use your data to provide and improve the Service. By using the Service, you agree to the collection and use of information in accordance with this policy. Unless otherwise defined in this Privacy Policy, terms used in this Privacy Policy have the same meanings as in our Terms and Conditions.</p>

      <h2 id="definitions">Definitions</h2>

      <h3 id="service">Service</h3>

      <p>Service means the Elephant Wallet mobile application operated by Elastos Application Lab.</p>

      <h3 id="partnerservice">Partner Service</h3>

      <p>Partner Service means a service or feature offered by a third-party partner directly to users of the Service.</p>

      <h3 id="personaldata">Personal Data</h3>

      <p>Personal Data means data about a living individual who can be identified from those data (or from those and other information either in our possession or likely to come into our possession).</p>

      <h3 id="usagedata">Usage Data</h3>

      <p>Usage Data is data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</p>

      <h3 id="cookies">Cookies</h3>

      <p>Cookies are small pieces of data stored on your device (computer or mobile device).</p>

      <h3 id="datacontroller">Data Controller</h3>

      <p>Data Controller means the natural or legal person who (either alone or jointly or in common with other persons) determines the purposes for which and the manner in which any personal information are, or are to be, processed.</p>

      <p>For the purpose of this Privacy Policy, we are a Data Controller of your Personal Data.</p>

      <h3 id="dataprocessorsorserviceproviders">Data Processors (or Service Providers)</h3>

      <p>Data Processor (or Service Provider) means any natural or legal person who processes the data on behalf of the Data Controller.</p>

      <p>We may use the services of various Service Providers in order to process your data more effectively.</p>

      <h3 id="datasubjectoruser">Data Subject (or User)</h3>

      <p>Data Subject is any living individual who is using our Service and is the subject of Personal Data.</p>

      <h2 id="informationcollectionanduse">Information Collection and Use</h2>

      <p>We collect several different types of information for various purposes to provide and improve our Service to you.</p>

      <h2 id="typesofdatacollected">Types of Data Collected</h2>

      <h3 id="personaldata-1">Personal Data</h3>

      <p>While using our Service, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you ("Personal Data").</p>

      <p>The following information may be collected by the Service:</p>

      <ul>
      <li>Cookies and Usage Data</li>
      </ul>

      <p>If you sign up for our beta test program, you will be asked to provide the following:</p>

      <ul>
      <li>Email address</li>
      </ul>

      <p>If you elect to use a Partner Service, the Partner Service may ask you to provide personally identifiable information including, but not limited to, the following:</p>

      <ul>
      <li>Email address</li>

      <li>First name and last name</li>

      <li>Phone number</li>

      <li>Address, State, Province, ZIP/Postal code, City</li>
      </ul>

      <p>If provided, your email address may be used to contact you with newsletters, marketing or promotional materials, and other information that may be of interest to you. You may opt out of receiving any, or all, of these communications from us by following the unsubscribe link or instructions provided in any email we send or by contacting us.</p>

      <h3 id="usagedata-1">Usage Data</h3>

      <p>We may also collect information that your browser sends whenever you visit our Service or when you access the Service by or through a mobile device ("Usage Data").</p>

      <p>This Usage Data may include information such as your computer's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that you visit, the time and date of your visit, the time spent on those pages, unique device identifiers, and other diagnostic data.</p>

      <p>When you access the Service by or through a mobile device, this Usage Data may include information such as the type of mobile device you use, your mobile device unique ID, the IP address of your mobile device, your mobile operating system, the type of mobile Internet browser you use, unique device identifiers and other diagnostic data.</p>

      <h3 id="locationdata">Location Data</h3>

      <p>We may use and store information about your location if you give us permission to do so (“Location Data”). We use this data to provide features of our Service, and to improve and customize our Service.</p>

      <p>You can enable or disable location services when you use our Service at any time, through your device settings.</p>

      <h3 id="trackingcookiesdata">Tracking Cookies Data</h3>

      <p>We use cookies and similar tracking technologies to track the activity on our Service and hold certain information.</p>

      <p>Cookies are files with small amount of data which may include an anonymous unique identifier. Cookies are sent to your browser from a website and stored on your device. Tracking technologies also used are beacons, tags, and scripts to collect and track information and to improve and analyze our Service.</p>

      <p>You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent.</p>

      <p>Examples of Cookies we use:</p>

      <ul>
      <li>Session Cookies. We use Session Cookies to operate our Service.</li>

      <li>Preference Cookies. We use Preference Cookies to remember your preferences and various settings.</li>

      <li>Security Cookies. We use Security Cookies for security purposes.</li>
      </ul>

      <h3 id="useofdata">Use of Data</h3>

      <p>Elastos Application Lab uses the collected data for various purposes:</p>

      <ul>
      <li>To provide and maintain our Service</li>

      <li>To allow you to participate in interactive features of our Service when you choose to do so</li>

      <li>To provide customer support</li>

      <li>To gather analysis or valuable information so that we can improve our Service</li>

      <li>To monitor the usage of our Service</li>

      <li>To detect, prevent and address technical issues</li>

      <li>To provide you with news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless you have opted not to receive such information</li>
      </ul>

      <h3 id="legalbasisforprocessingpersonaldataundergeneraldataprotectionregulationgdpr">Legal Basis for Processing Personal Data Under General Data Protection Regulation (GDPR)</h3>

      <p>If you are from the European Economic Area (EEA), Elastos Application Lab’s legal basis for collecting and using the personal information described in this Privacy Policy depends on the Personal Data we collect and the specific context in which we collect it.</p>

      <p>Elastos Application Lab may process your Personal Data because:</p>

      <ul>
      <li>We need to perform a contract with you</li>

      <li>You have given us permission to do so</li>

      <li>The processing is in our legitimate interests and is not overridden by your rights</li>

      <li>It is required to comply with the law</li>
      </ul>

      <h3 id="retentionofdata">Retention of Data</h3>

      <p>Elastos Application Lab will retain your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.</p>

      <p>Elastos Application Lab will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period of time, except when this data is used to strengthen the security or to improve the functionality of our Service, or we are legally obligated to retain this data for longer time periods.</p>

      <h3 id="transferofdata">Transfer of Data</h3>

      <p>Your information, including Personal Data, may be transferred to — and maintained on — computers located outside of your state, province, country or other governmental jurisdiction where the data protection laws may differ than those from your jurisdiction.</p>

      <p>Your consent to this Privacy Policy followed by your submission of such information represents your agreement to that transfer.</p>

      <p>Elastos Application Lab will take all steps reasonably necessary to ensure that your data is treated securely and in accordance with this Privacy Policy and no transfer of your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of your data and other personal information.</p>

      <h2 id="disclosureofdata">Disclosure of Data</h2>

      <h3 id="legalrequirements">Legal Requirements</h3>

      <p>Elastos Application Lab may disclose your Personal Data in the good faith belief that such action is necessary to:</p>

      <ul>
      <li>To comply with a legal obligation</li>

      <li>To protect and defend the rights or property of Elastos Application Lab</li>

      <li>To prevent or investigate possible wrongdoing in connection with the Service</li>

      <li>To protect the personal safety of users of the Service or the public</li>

      <li>To protect against legal liability</li>
      </ul>

      <h3 id="securityofdata">Security of Data</h3>

      <p>The security of your data is important to us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While we strive to use commercially acceptable means to protect your Personal Data, we cannot guarantee its absolute security.</p>

      <h3 id="yourdataprotectionrightsundergeneraldataprotectionregulationgdpr">Your Data Protection Rights Under General Data Protection Regulation (GDPR)</h3>

      <p>If you are a resident of the European Economic Area (EEA), you have certain data protection rights. Elastos Application Lab aims to take reasonable steps to allow you to correct, amend, delete, or limit the use of your Personal Data.</p>

      <p>If you wish to be informed what Personal Data we hold about you and if you want it to be removed from our systems, please contact us.</p>

      <p>In certain circumstances, you have the following data protection rights:</p>

      <p>The right to access, update or to delete the information we have on you. Whenever made possible, you can access, update or request deletion of your Personal Data directly within your account settings section. If you are unable to perform these actions yourself, please contact us to assist you.</p>

      <p>The right of rectification. You have the right to have your information rectified if that information is inaccurate or incomplete.</p>

      <p>The right to object. You have the right to object to our processing of your Personal Data.</p>

      <p>The right of restriction. You have the right to request that we restrict the processing of your personal information.</p>

      <p>The right to data portability. You have the right to be provided with a copy of the information we have on you in a structured, machine-readable and commonly used format.</p>

      <p>The right to withdraw consent. You also have the right to withdraw your consent at any time where Elastos Application Lab relied on your consent to process your personal information.</p>

      <p>Please note that we may ask you to verify your identity before responding to such requests.</p>

      <p>You have the right to complain to a Data Protection Authority about our collection and use of your Personal Data. For more information, please contact your local data protection authority in the European Economic Area (EEA).</p>

      <h3 id="serviceproviders">Service Providers</h3>

      <p>We may employ third party companies and individuals to facilitate our Service ("Service Providers"), to provide the Service on our behalf, to perform Service-related services or to assist us in analyzing how our Service is used.</p>

      <p>These third parties have access to your Personal Data only to perform these tasks on our behalf and are obligated not to disclose or use it for any other purpose.</p>

      <h3 id="analytics">Analytics</h3>

      <p>We may use third-party Service Providers to monitor and analyze the use of our Service.</p>

      <p>Tencent Bugly</p>

      <p>Tencent Bugly is one of Tencent's services for mobile developers. Provide professional developers with abnormal reporting and operational statistics to help developers quickly identify and resolve anomalies, while keeping abreast of product operations and keeping up with user feedback.</p>

      <p>Elephant integrates the bugly feature, the main function is to capture the crash information and application upgrade of the Elephant application.</p>

      <p>User information is not collected when upgrading information.</p>

      <p>Information collected by the Crash log:</p>

      <ul>
      <li>Application version</li>

      <li>Equipment model</li>

      <li>ROM information</li>

      <li>CPU architecture</li>

      <li>android system version</li>

      <li>Network APN</li>

      <li>Is ROOT?</li>

      <li>Memory size / available storage space</li>

      <li>sd size</li>
      </ul>

      <p>For more information on Tencent's Bugly privacy practices, please visit the Tencent Bugly User Agreement page: <a href="https://bugly.qq.com/v2/contract">https://bugly.qq.com/v2/contract</a></p>

      <h3 id="linkstoothersites">Links To Other Sites</h3>

      <p>Our Service may contain links to other sites that are not operated by us. If you click on a third party link, you will be directed to that third party's site. We strongly advise you to review the Privacy Policy of every site you visit.</p>

      <p>We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.</p>

      <h3 id="childrensprivacy">Children's Privacy</h3>

      <p>Our Service does not address anyone under the age of 18 ("Children").</p>

      <p>We do not knowingly collect personally identifiable information from anyone under the age of 18. If you are a parent or guardian and you are aware that your Children has provided us with Personal Data, please contact us. If we become aware that we have collected Personal Data from children without verification of parental consent, we take steps to remove that information from our servers.</p>

      <h3 id="changestothisprivacypolicy">Changes To This Privacy Policy</h3>

      <p>We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page, and will update the "effective date" at the top of this Privacy Policy.</p>

      <p>You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.</p>

      <h3 id="contactus">Contact Us</h3>

      <p>If you have any questions about this Privacy Policy, please contact us by email: support@elaphant.app</p>
    </Inner>
  </Container>
)

const Container = styled.div`

`
const Inner = styled.div`
  padding: 60px 100px;
  @media only screen and (max-width: ${breakPoint.mobile}) {
    padding: 30px 20px;
  }
`

const Spacer = styled.div`
  background-color: #FE5551;
  height: 60px;
`